#ifndef MINING_TEST_BINDINGS_H
#define MINING_TEST_BINDINGS_H

#include <stdlib.h>
#include "mining_allocator_fault_injector.h"

/* Give the private test instance unique symbols so unrelated tests and system
 * tasks cannot consume an injected allocation failure. */
#define allocate_bm_job mining_test_allocate_bm_job
#define retain_bm_job mining_test_retain_bm_job
#define release_bm_job mining_test_release_bm_job
#define free_bm_job mining_test_free_bm_job
#define calculate_coinbase_tx_hash_bin mining_test_calculate_coinbase_tx_hash_bin
#define calculate_merkle_root_hash mining_test_calculate_merkle_root_hash
#define construct_bm_job_from_miner_job mining_test_construct_bm_job_from_miner_job
#define extranonce_2_generate mining_test_extranonce_2_generate
#define extranonce_2_increment mining_test_extranonce_2_increment
#define mining_v1_effective_share_difficulty mining_test_v1_effective_share_difficulty
#define mining_share_solves_block mining_test_share_solves_block
#define hash_to_pdiff mining_test_hash_to_pdiff
#define test_nonce_value mining_test_nonce_value
#define increment_bitmask mining_test_increment_bitmask
#define version_mask_midstate_count mining_test_version_mask_midstate_count
#define version_mask_value_count mining_test_version_mask_value_count

#define malloc(size) mining_allocator_fault_injector_malloc(size)
#define calloc(count, size) mining_allocator_fault_injector_calloc(count, size)

#endif
